version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    expose:
      - "27017"
    command: [--auth]
  backend:
    container_name: backend
    depends_on:
      - mongodb
    #image: arowx/sia-manager:latest
    build: ./backend
    env_file: ./.env
    expose:
      - "8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  frontend:
    image: nginx:alpine
    container_name: frontend
    expose:
      - "8080"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  nginx_reverse_proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  mongodb:
  db:
